---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      volumes:
      - name: appdata
        persistentVolumeClaim:
          claimName: appdata-pvc
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        ports:
        - name: "api"
          containerPort: 7777
          protocol: TCP
        - name: "game"
          containerPort: 7777
          protocol: UDP
        - name: "messaging"
          containerPort: 8888
          protocol: TCP
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: UMASK
          value: "000"
        - name: "MAXPLAYERS"
          value: "4"
        - name: "SERVERGAMEPORT"
          value: "7777"
        - name: "TIMEOUT"
          value: "120"
        volumeMounts:
        - mountPath: "/config"
          subPath: "satisfactory"
          name: appdata

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.28.15
  externalTrafficPolicy: Local
  selector:
    app: {{ .Values.name }}
  ports:
    - name: game
      protocol: TCP
      port: 7777
      targetPort: 7777
    - name: gameudp
      protocol: UDP
      port: 7777
      targetPort: 7777
    - name: messaging
      protocol: TCP
      port: 8888
      targetPort: 8888
