apiVersion: v2
name: storage-sentinel
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: kube-prometheus-stack
    version: 83.6.0
    repository: "oci://ghcr.io/prometheus-community/charts"
