kube-prometheus-stack:
  defaultRules:
    create: false

  grafana:
    enabled: false

  alertmanager:
    enabled: false

  kubeControllerManager:
    enabled: false

  kubeScheduler:
    enabled: false

  kubeEtcd:
    enabled: false

  prometheus:
    prometheusSpec:
      retention: 1h
      serviceMonitorSelectorNilUsesHelmValues: true
      podMonitorSelectorNilUsesHelmValues: true
      probeSelectorNilUsesHelmValues: true
