authentik:
    authentik:
        secret_key: ENC[AES256_GCM,data:7OJ2YQ390UvZXvTz+1y5cxkBFe4WOai+shaKLrjMUmesDuBC,iv:Oy9MkZ8e/xXq9K3jdDZQQ+JXy5Y2LjuPshwhhUY0zv0=,tag:u5TaBN44o9mDovxk+9q7kg==,type:str]
        postgresql:
            user: ENC[AES256_GCM,data:HuaIQMnaElms,iv:V+xZ31M2vwQ9ybUOTj5yTunQ4FAnccBwkUfADJa73vo=,tag:7yrqzCnJHSzae0TLNg0D2Q==,type:str]
            password: ENC[AES256_GCM,data:4GTlakxvjggSdScHwgCzn+QPd0J8s3VbTP7yQwtQeA==,iv:7nbKmHW1e69zNjCHnbbwZsy8rBGJ9wMJLoHGo7K/Vs4=,tag:dwkupTG4TEGGldVio5eCWQ==,type:str]
        bootstrap_password: ENC[AES256_GCM,data:gUJjDug3biRaaMzR91y18XxcEv35j1je7UwhmBf8Xp3V6GUoL8W2rd7j7BquoEJiYQuGJ6rjjiRo4E7W5um0Lg==,iv:P1A1DS4fSY1avstL4UgU1tE5H6y6FCGnHQ3rLnd2HH0=,tag:8daCfxgnDOlim8p7es1Yjg==,type:str]
        bootstrap_token: ENC[AES256_GCM,data:4GyBwNg4GIexPzrxnMvNTpoTE60Yf9+rD52sWYAUVh224PGYRyvV8zeiG5NYcFDa0GVM0f0FzIRm2w==,iv:5VhRe2MfJcNzeYelN3P2NEH1yWoQ5qv9kcyGy0HL9GY=,tag:THERZdklGxsNRBGjColfqQ==,type:str]
        bootstrap_email: ENC[AES256_GCM,data:RAaCpe56+av0Dzh81MjU1Pw=,iv:p5MTQjt+zIE7BwTwWNilSdOKpzhDNJvzcAUNbKSDbDs=,tag:SxRSLVPKZtx+bbLhIwQgHQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ca-central-1:490881312659:alias/Deployment
          created_at: "2025-06-09T18:19:36Z"
          enc: AQICAHjS4ENnSiVJmrdNfAAxWWjSzWh6nSsXgc38CA5Ml5cfJAEawLFvXusAEhUBOqCdfgbiAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMj1SYealxS0BJihy+AgEQgDs3v6ioO8Trc/lzDKFrW7pYig54ZRxssWYvjTyxgI/BVNaaRIfRWYYgAF64Eds5fcaFAhJB+FLgmW8yVQ==
          aws_profile: ""
    lastmodified: "2025-08-17T02:48:29Z"
    mac: ENC[AES256_GCM,data:Hhdv/GV34yILCH264KKjixaMj3XT68GHt9BZWE1Pde1BY7Lg+svTkb6DBaTD1SXZXwd8vtIXTnjPqGPen2KPAQJzbdvRBMeVZ9CuDabJeQ0+grEPvEJGT1u2AU39FPKmcTIe6eo9XgKgn7mOhPKZuTaR23Bs0dGzpbPN4HlN28A=,iv:UcJTvpc8u0Y9S8IXMK2OvpgY+Zk+YGExv3J5ETqiCrg=,tag:OwrOjv7ss+Rs399v4L6pWQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
