- name: Install CUDA
  include_tasks: cuda.yml
  when: cuda_install is defined and cuda_install

- name: Install Koboldcpp
  include_tasks: koboldcpp.yml
  when: koboldcpp_install is defined and koboldcpp_install
