global:
    password: ENC[AES256_GCM,data:2s9f3GK2,iv:4B0CWFiXXbDAyIuJZ+Br+2bBYJOPTfkKWQbBBjb7+3I=,tag:Ai/c2ffw96Vg9WR/3ylj7w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ca-central-1:490881312659:alias/Deployment
          created_at: "2026-08-30T17:51:29Z"
          enc: AQICAHjS4ENnSiVJmrdNfAAxWWjSzWh6nSsXgc38CA5Ml5cfJAHwruKRJs5BzsrgMlZ0dHcDAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5HGks8FgIy93tOf0AgEQgDvyPf6+BD+goLzglhP5GVLLDEzwVsK4FappbxiKg8Boahio5CkmI5mF9TT/UXEHHBcnwFZOb9PKzk94xg==
          aws_profile: ""
    lastmodified: "2026-08-30T17:55:36Z"
    mac: ENC[AES256_GCM,data:qsA1Mg+bgIX1OxgORSUJqnvkZG+CBXShb5a0Pz+vCMNb+ooQhYMdhkOABnK2/UYmwWAQmoeZMLFCjE/+SM7N3DwJ2kX0M0DdCFNXIM/GBpPjg0OqAfsYZkdgaU6xc4sHfhe4ORKl6S8FhQYg/J9v96TVuAznHlaQs7SFjIM9eQc=,iv:kfLad00AQSqiiPlCd4zMgqYp41f+qIwZElyavdiXx/E=,tag:UKHnrH1kl513NaTLQKINOg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
