---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: riftbreaker=registry.home.ryougi.ca/riftbreaker:latest
    argocd-image-updater.argoproj.io/riftbreaker.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/riftbreaker.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/riftbreaker.update-strategy: digest
  name: app-riftbreaker
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: apps
  project: default
  source:
    path: argocd/app-games/riftbreaker
    repoURL: https://github.com/kumorikarasu/home.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
