tmodloader:
    password: ENC[AES256_GCM,data:OU76ZltTHM6XmQ+A,iv:BtpKbhXuMNHFxo1lk14UC8Zk1c9gXaL80h8Uug9zFLY=,tag:UvqPixZhopgLuOUTA/hToA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ca-central-1:490881312659:alias/Deployment
          created_at: "2023-01-26T19:06:30Z"
          enc: AQICAHjS4ENnSiVJmrdNfAAxWWjSzWh6nSsXgc38CA5Ml5cfJAHZAd5DtGg2TUEVwZfvqIiMAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMS6ACWyAnZ8kxw1SIAgEQgDsGl/xkaKsTTQbWpoOOMJQ2TIVt8fC0vVQj4bgcNIYEVESn5goTp2d4Z9tSEZtgLkVU0YbGxy1h5BSydg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-01T23:29:34Z"
    mac: ENC[AES256_GCM,data:fa8dg3hW98EGyK4LeDaj6BIquPdwtalXBGCRgBgsHP1ckvlNVSdjC63Lx2+2TesiYzmCXy7nQ8ZESMt2RC9g69zWZaP2z9S9Fy1/WZHtVtmUCeYR8CxX+bmloNTvg7eNGDaYaeEgMVtUBNCks4BQNZEVNJoMk7oDsIUEXuIpSUA=,iv:lQb/ao4FnUmezpsIDAa2AywmrR5r29g7VcXa2QQVZWQ=,tag:+J0VAqw4GUlUJSEljIQ9XA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
