---
apiVersion: v1
kind: Pod
metadata:
  name: iscsipd
spec:
  containers:
  - name: iscsipd-rw
    # image: wbitt/network-multitool
    # image: ubuntu
    image: binhex/arch-radarr
    volumeMounts:
    - mountPath: "/config"
      name: iscsipd-rw
  volumes:
  - name: iscsipd-rw
    iscsi:
      targetPortal: 192.168.1.21:3260
      iqn: iqn.2005-10.org.freenas.ctl:k8s
      lun: 0
      fsType: ext4
      readOnly: false

---
apiVersion: v1
kind: Pod
metadata:
  name: iscsipd2
spec:
  containers:
  - name: iscsipd-rw2
    # image: wbitt/network-multitool
    # image: ubuntu
    image: binhex/arch-radarr
    volumeMounts:
    - mountPath: "/config"
      name: iscsipd-rw
  volumes:
  - name: iscsipd-rw
    iscsi:
      targetPortal: 192.168.1.21:3260
      iqn: iqn.2005-10.org.freenas.ctl:k8s.radarr
      lun: 1
      fsType: ext4
      readOnly: false
