
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
spec:
  type: ExternalName
  externalName: nexus.static.home.ryougi.ca

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - nexus.home.ryougi.ca
      - docker.home.ryougi.ca
  rules:
  - host: nexus.ryougi.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nexus-service
            port:
              number: 8081
  - host: nexus.home.ryougi.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nexus-service
            port:
              number: 8081
  - host: docker-kube.home.ryougi.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nexus-service
            port:
              number: 5000
