---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: router-peer
  namespace: {{ .Release.Namespace }}
spec:
  myASN: 64500
  peerASN: 64502
  peerAddress: 192.168.1.1


---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: local-pool
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
  - 192.168.2.10-192.168.2.254


---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: example
  namespace: {{ .Release.Namespace }}
