---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-truenas-secret"
  namespace: {{ .Release.Namespace }}
stringData:
  serviceName: "{{ .Release.Name }}-truenas-csp-svc"
  servicePort: "8080"
  username: {{ .Values.storage.username }}
  password: {{ .Values.storage.password }}
  backend: {{ .Values.storage.backend }}
