---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appdata-pvc
spec:
  volumeName: appdata-pv
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1000Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: appdata-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1000Gi
  nfs:
    path: /mnt/Backup/appdata
    server: 192.168.1.21
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
