---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    helm: 
      valueFiles:
      - values.yaml
    path: argocd/argo
    repoURL: https://github.com/kumorikarasu/home.git
  syncPolicy:
    automated:
      selfHeal: true
