apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-appset
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
    - git:
        repoURL: https://github.com/kumorikarasu/home.git
        revision: HEAD
        directories:
          - path: argocd/platform/*
  template:
    metadata:
      name: 'platform-{{path.basename}}'
    spec:
      project: platform
      source:
        repoURL: https://github.com/kumorikarasu/home.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        name: in-cluster
        namespace: monitoring
      syncPolicy:
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - ServerSideApply=true
          - SkipDryRunOnMissingResource=true
