apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: {{ .Release.Namespace }}
spec:
  destination:
    name: in-cluster
    namespace: {{ .Release.Namespace }}
  project: default
  source:
    path: argocd/platform
    repoURL: https://github.com/kumorikarasu/home.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
