---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr-deployment
  labels:
    app: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      volumes:
      - name: qbt
        persistentVolumeClaim:
          claimName: qbt-pvc
      - name: qbt-media
        persistentVolumeClaim:
          claimName: qbt-media-pvc
      containers:
      - name: prowlarr
        image: binhex/arch-prowlarr
        ports:
        - containerPort: 9696
        env:
        - name: UMASK
          value: "000"
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        volumeMounts:
        - mountPath: "/Media"
          subPath: "Movies"
          name: qbt-media
        - mountPath: "/data"
          subPath: "prowlarr/data"
          name: qbt
        - mountPath: "/config"
          subPath: "prowlarr/config"
          name: qbt

---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr-service
spec:
  selector:
    app: prowlarr
  ports:
    - name: http
      protocol: TCP
      port: 9696
      targetPort: 9696

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  name: prowlarr-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: prowlarr.ryougi.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prowlarr-service
            port:
              number: 9696
