---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
  namespace: apps
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
stringData:
  # Values will come from SOPS secrets.enc.yaml merge  
  AUTHENTIK_SECRET_KEY: "{{ .Values.authentik.authentik.secret_key }}"
  AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .Values.authentik.authentik.postgresql.password }}"
  AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .Values.authentik.authentik.bootstrap_password }}"
  AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .Values.authentik.authentik.bootstrap_token }}"
