---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraria14-deployment
  labels:
    app: terraria14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraria14
  template:
    metadata:
      labels:
        app: terraria14
    spec:
      volumes:
      - name: appdata
        persistentVolumeClaim:
          claimName: appdata-pvc
      containers:
      - name: terraria14
        image: kumorikarasu/tmodloader:v2022.08.54.4
        imagePullPolicy: Always
        env:
        - name: DATA_DIR
          value: "/serverdata"
        ports:
        - containerPort: 7777
        volumeMounts:
        - mountPath: "/serverdata"
          subPath: terraria14/tmodloader
          name: appdata
        - mountPath: "/terrariadata/tModLoader/tModLoader-Logs"
          subPath: terraria14/tmodloader-logs
          name: appdata
        

---
apiVersion: v1
kind: Service
metadata:
  name: terraria14-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.2.13
  selector:
    app: terraria14
  ports:
    - name: app
      protocol: TCP
      port: 7777
      targetPort: 7777
