---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment"
  labels:
    app: "{{ .Release.Name }}-tgwu"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-tgwu"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-tgwu"
    spec:
      runtimeClassName: nvidia
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.present
                operator: In
                values: ["true"]
      volumes:
      - name: appdata
        persistentVolumeClaim:
          claimName: appdata-pvc
      - name: "{{ .Release.Name }}-config"
        configMap:
          name: "{{ .Release.Name }}-config"
          items:
          - key: config.conf
            path: config.conf
      volumes:
      - name: local-pv
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-local-pvc"
      - name: cmd-config
        configMap:
          name: "{{ .Release.Name }}-config"
      containers:
      - name: tgwu 
        image: registry.home.ryougi.ca/tgwu
        # No GPU resource limits - use runtime class and env vars for GPU access
        ports:
        - containerPort: 7860
        - containerPort: 5000
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: UMASK
          value: "000"
        - name: PORT
          value: "8000"
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "all"
        volumeMounts:
        - mountPath: "/home/app/text-generation-webui/user_data/models"
          name: local-pv
        - mountPath: "/home/app/text-generation-webui/user_data/CMD_FLAGS.txt"
          subPath: CMD_FLAGS.txt
          name: cmd-config

      
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"
spec:
  selector:
    app: "{{ .Release.Name }}-tgwu"
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 7860
    - name: api
      protocol: TCP
      port: 5000
      targetPort: 5000

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-local-pvc"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 128Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Release.Name }}-local-pv"
spec:
  capacity:
    storage: 128Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/volumes/local-volume-cache
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node4
          - node5

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  name: "{{ .Release.Name }}-ingress"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - ryougi.ca
  rules:
  - host: tgwu.kube.home.ryougi.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Release.Name }}-service"
            port:
              number: 80
  - host: tgwu.kube.ryougi.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Release.Name }}-service"
            port:
              number: 80
  - host: tgwu.home.ryougi.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Release.Name }}-service"
            port:
              number: 80
  - host: tgwu.ryougi.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Release.Name }}-service"
            port:
              number: 80
              
# CMD_FLAGS configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
data: 
  CMD_FLAGS.txt: |
    --listen
    --api


