{{- range $i, $runnerCfg := .Values.runnerDeployments }}
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ printf "%s-%s" $.Release.Name $runnerCfg.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $runnerCfg.name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ include "github-runner.chart" $ }}
    github-runner-config: {{ $runnerCfg.name }}
    github-runner-org: {{ $runnerCfg.organization }}
spec:
  replicas: {{ $runnerCfg.replicas }}
  template:
    spec:
      organization: {{ $runnerCfg.organization }}
      image: {{ $runnerCfg.image }}
      githubAPICredentialsFrom:
        secretRef:
          name: {{ printf "%s-%s-credentials" $.Release.Name $runnerCfg.organization | trunc 63 | trimSuffix "-" }}
      {{- if $runnerCfg.labels }}
      labels:
      {{- toYaml $runnerCfg.labels | nindent 8 }}
      {{- end }}
      {{- if $runnerCfg.resources }}
      resources:
      {{- toYaml $runnerCfg.resources | nindent 8 }}
      {{- end }}
{{- end }}
