---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-kumorikarasu-credentials" .Release.Name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "github-runner.name" . }}
    helm.sh/chart: {{ include "github-runner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    github-runner-org: kumorikarasu
type: Opaque
stringData:
  github_app_id: {{ .Values.kumorikarasu_github_app_id | quote }}
  github_app_installation_id: {{ .Values.kumorikarasu_github_app_installation_id | quote }}
  github_app_private_key: {{ .Values.kumorikarasu_github_app_private_key | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-bayoudb-credentials" .Release.Name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "github-runner.name" . }}
    helm.sh/chart: {{ include "github-runner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    github-runner-org: bayoudb
type: Opaque
stringData:
  github_app_id: {{ .Values.bayoudb_github_app_id | quote }}
  github_app_installation_id: {{ .Values.bayoudb_github_app_installation_id | quote }}
  github_app_private_key: {{ .Values.bayoudb_github_app_private_key | quote }}
