apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-runner.appSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "github-runner.name" . }}
    helm.sh/chart: {{ include "github-runner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  github_app_id: {{ .Values.github_app_id | quote }}
  github_app_installation_id: {{ .Values.github_app_installation_id | quote }}
  github_app_private_key: {{ .Values.github_app_private_key | quote }}
