image:
  repository: registry.home.ryougi.ca/wrbgc-site
  tag: latest
  pullPolicy: Always

replicaCount: 1

service:
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - wrbgc.ca
    - wrbgc.home.ryougi.ca
    - dev.wrbgc.ca
    - dev.wrbgc.home.ryougi.ca
  tls:
    enabled: true
    secretName: wrbgc-ca-tls

resources: {}

sync:
  enabled: true
  replicaCount: 1
  reconcileIntervalSeconds: "3600"
  image:
    repository: registry.home.ryougi.ca/wrbgc-sync
    tag: latest
    pullPolicy: Always
  secretName: wrbgc-sync-env
  discordGuildId: "1238671986746720388"
  discordAnnouncementsChannelId: "1239589618127605771"
  googleCalendarId: "afdaf942b172185e5580aad344ed164cdf2d862b6d170e7dc6bc0e924cdda9b4@group.calendar.google.com"
  resources: {}
