argo-cd:
  server:
    extraArgs:
      - --insecure
    ingress:                                                                                                                                                                                                                                                      
      enabled: true
      hosts: ["argocd.home.ryougi.ca", "argocd.ryougi.ca"]
      ingressClassName: "nginx"

  repoServer:
    extraContainers:
    - name: cmp
      command: [/var/run/argocd/argocd-cmp-server] # Entrypoint should be Argo CD lightweight CMP server i.e. argocd-cmp-server
      image: kumorikarasu/helm-sops
      env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-token-secret
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-token-secret
            key: AWS_SECRET_ACCESS_KEY
      - name: HELM_CACHE_HOME
        value: /helm-working-dir
      - name: HELM_CONFIG_HOME
        value: /helm-working-dir
      - name: HELM_DATA_HOME
        value: /helm-working-dir
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - name: var-files
          mountPath: /var/run/argocd
        - name: plugins
          mountPath: /home/argocd/cmp-server/plugins
        - name: cmp-plugin
          mountPath: /home/argocd/cmp-server/config/plugin.yaml # Plugin config file can either be volume mapped or baked into image
          subPath: plugin.yaml
        - name: cmp-tmp
          mountPath: /tmp
        - name: helm-temp-dir
          mountPath: /helm-working-dir
    volumes:
      - name: cmp-plugin
        configMap:
          name: cmp-plugin
      - name: cmp-tmp
        emptyDir: {}
      - name: helm-temp-dir
        emptyDir: {}
