argo-cd:
  server:
    extraArgs:
      - --insecure
    ingress:                                                                                                                                                                                                                                                      
      enabled: true
      hosts: ["argocd.ryougi.ca"]
      ingressClassName: "nginx"
