argo-cd:
  server:
    extraArgs:
      - --insecure
    ingress:                                                                                                                                                                                                                                                      
      enabled: true
      hosts: ["argocd.ryougi.ca"]
      ingressClassName: "nginx"

  repoServer:
    extraContainers:
    - name: cmp
      command: [/var/run/argocd/argocd-cmp-server] # Entrypoint should be Argo CD lightweight CMP server i.e. argocd-cmp-server
      image: mozilla/sops
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml # Plugin config file can either be volume mapped or baked into image
          subPath: plugin.yaml
          name: cmp-plugin
    volumes:
      - configMap:
          name: cmp-plugin
        name: cmp-plugin
