---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmodloader-deployment
  labels:
    app: tmodloader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tmodloader
  template:
    metadata:
      labels:
        app: tmodloader
    spec:
      volumes:
      - name: appdata
        persistentVolumeClaim:
          claimName: appdata-pvc
      - name: serverconfig
        configMap:
          name: tmodloader-config
      containers:
      - name: tmodloader
        imagePullPolicy: Always
        image: kumorikarasu/tmodloader:v2023.06.25.27
        args:
          - '-password $(password)'
        ports:
        - containerPort: 7777
        env:
        - name: password
          valueFrom:
            secretKeyRef:
              name: tmodloader-secret
              key: password
        - name: DATA_DIR
          value: "/serverdata"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: UMASK
          value: "000"
        volumeMounts:
        - mountPath: "/serverdata"
          subPath: tmodloader/serverdata
          name: appdata
        - mountPath: "/terrariadata/tModLoader/tModLoader-Logs"
          subPath: tmodloader/logs
          name: appdata
        - name: serverconfig
          mountPath: "terrariadata/tModLoader/serverconfig.txt"
          subPath: "serverconfig.txt"

          


---
apiVersion: v1
kind: Service
metadata:
  name: tmodloader-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.2.13
  selector:
    app: tmodloader
  ports:
    - name: app
      protocol: TCP
      port: 7777
      targetPort: 7777


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tmodloader-config
data:
  serverconfig.txt: |
    # tModLoader Server Config
    # This is the config file for tModLoader Server.
    autocreate=3
    world=/serverdata/worlds/world1.wld
    worldpath=/serverdata/worlds
    worldname=WHAL
    seed=world1seed
    difficulty=1
    maxplayers=8
    motd=Welcome to Terraria!
    port=7777
    autoshutdown=0
    priority=1

---
apiVersion: v1
kind: Secret
metadata:
  name: tmodloader-secret
data:
  password: {{ .Values.tmodloader.password | b64enc }}
type: Opaque
