---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio-plus-deployment
  labels:
    app: factorio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factorio-plus
  template:
    metadata:
      labels:
        app: factorio-plus
    spec:
      hostNetwork: true
      volumes:
      - name: appdata
        persistentVolumeClaim:
          claimName: appdata-pvc
      containers:
      - name: factorio
        image: factoriotools/factorio:1.1.74
        ports:
        - containerPort: 34199
          hostPort: 34199
        - containerPort: 27019
          hostPort: 27019
        env:
        - name: PUID
          value: "99"
        - name: PGID
          value: "100"
        - name: PORT
          value: "34199"
        - name: RCON_PORT
          value: "27018"
        - name: GENERATE_NEW_SAVE
          value: "true"
        - name: SAVE_NAME
          value: "factorio_server"
        - name: LOAD_LATEST_SAVE
          value: "false"
        - name: UPDATE_MODS_ON_START
          value: "true"
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: factorio-modded-secret
              key: username
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: factorio-modded-secret
              key: token
        volumeMounts:
        - mountPath: "/factorio"
          subPath: "factorio/vanilla-plus"
          name: appdata


---
apiVersion: v1
kind: Service
metadata:
  name: factorio-plus-service
spec:
  loadBalancerIP: 192.168.2.14
  type: LoadBalancer
  selector:
    app: factorio-plus
  ports:
    - name: game
      protocol: TCP
      port: 27018
      targetPort: 27018
    - name: gameudp
      protocol: UDP
      port: 34199
      targetPort: 34199
