eso:
  installCRDs: true
  replicaCount: 2
  
  extraArgs:
    concurrent: 1
    store-requeue-interval: 24h
  
  serviceAccount:
    create: true
    annotations:
    name: external-secrets
  
  env:
    AWS_REGION: ca-central-1
    AWS_DEFAULT_REGION: ca-central-1
  
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
      
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65532
    capabilities:
      drop:
      - ALL
