---
# PostgreSQL secrets for crocodile
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crocodile-postgres-secrets
  namespace: crocodile
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: crocodile-postgres-secrets
    creationPolicy: Owner
  data:
  - secretKey: postgres-password
    remoteRef:
      key: /home/k8s/crocodile/postgres
      property: admin_password
  - secretKey: username
    remoteRef:
      key: /home/k8s/crocodile/postgres
      property: username
  - secretKey: password
    remoteRef:
      key: /home/k8s/crocodile/postgres
      property: password
  - secretKey: database
    remoteRef:
      key: /home/k8s/crocodile/postgres
      property: database
  - secretKey: postgres-url
    remoteRef:
      key: /home/k8s/crocodile/postgres
      property: postgres_url

---
# ClickHouse secrets for crocodile
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crocodile-clickhouse-secrets
  namespace: crocodile
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: crocodile-clickhouse-secrets
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: /home/k8s/crocodile/clickhouse
      property: username
  - secretKey: password
    remoteRef:
      key: /home/k8s/crocodile/clickhouse
      property: password
  - secretKey: admin-password
    remoteRef:
      key: /home/k8s/crocodile/clickhouse
      property: admin_password