---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzb-deployment
  labels:
    app: nzb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nzb
  template:
    metadata:
      labels:
        app: nzb
    spec:
      volumes:
      - name: appdata
        persistentVolumeClaim:
          claimName: appdata-pvc
      - name: media
        persistentVolumeClaim:
          claimName: media-pvc
      containers:
      - name: nzb
        image: binhex/arch-sabnzbdvpn
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME"]
        ports:
        - containerPort: 8080
        - containerPort: 8090
        - containerPort: 8118
        env:
        - name: VPN_ENABLED
          value: "yes"
        - name: VPN_PROV
          value: "pia"
        - name: VPN_CLIENT
          value: "openvpn"
        - name: VPN_USER
          valueFrom:
            secretKeyRef:
              name: qbt-secret
              key: username
        - name: VPN_PASS
          valueFrom:
            secretKeyRef:
              name: qbt-secret
              key: password
        - name: ENABLE_PRIVOXY
          value: "yes"
        - name: LAN_NETWORK
          value: "192.168.0.0/16"
        - name: NAME_SERVERS
          value: "84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1"
        - name: VPN_INPUT_PORTS
          value: "1234"
        - name: VPN_OUTPUT_PORTS
          value: "5678"
        - name: DEBUG
          value: "false"
        - name: WEBUI_PORT
          value: "8080"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: UMASK
          value: "000"
        volumeMounts:
        - mountPath: "/Media"
          name: media
        - mountPath: "/data"
          subPath: "qbt/nzb/data"
          name: appdata
        - mountPath: "/config"
          subPath: "qbt/nzb/config"
          name: appdata


---
apiVersion: v1
kind: Service
metadata:
  name: nzb-service
spec:
  selector:
    app: nzb
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http2
      protocol: TCP
      port: 8090
      targetPort: 8090
    - name: privoxy
      protocol: TCP
      port: 8118
      targetPort: 8118

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  name: nzb-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - ryougi.ca
  rules:
  - host: nzb.ryougi.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nzb-service
            port:
              number: 8080
  - host: nzb.home.ryougi.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nzb-service
            port:
              number: 8080
