name: minecraft-atm10-v8

image:
  name: itzg/minecraft-server
  tag: java21

service:
  type: LoadBalancer
  loadBalancerIP: 192.168.28.21
  externalTrafficPolicy: Local
  port: 25565

startupProbe:
  enabled: true
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 120

storage:
  existingClaim: appdata-pvc
  subPath: minecraft/ATM10.8

minecraft:
  eula: "TRUE"
  type: NEOFORGE
  version: "1.21.1"
  memory: 40G
  difficulty: hard
  uid: "1000"
  gid: "1000"
  umask: "000"
  ops: kumorikarasu
  neoforgeVersion: "21.1.247"
  motd: ""
  maxPlayers: ""
  viewDistance: "8"
  simulationDistance: "6"
