---
- name: Kubernetes Storage Node Preparation
  hosts:
    - kube_node
    - kube_control_plane
    - etcd
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - k8s-storage
