---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment"
  labels:
    app: "{{ .Release.Name }}-tavern"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-tavern"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-tavern"
    spec:
      volumes:
      - name: config-dir
        emptyDir: {}
      - name: appdata
        persistentVolumeClaim:
          claimName: appdata-pvc
      - name: "{{ .Release.Name }}-config"
        configMap:
          name: "{{ .Release.Name }}-config"
          items:
          - key: config.yaml
            path: config.yaml
      initContainers:
      - name: copy
        image: busybox
        volumeMounts:
        - name: "{{ .Release.Name }}-config"
          mountPath: /home/node/app/config/config.yaml
          subPath: config.yaml
        - name: config-dir
          mountPath: /config
        command: ['sh', '-c', 'cp /home/node/app/config/config.yaml /config/config.yaml']
      containers:
      - name: tavern
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8000
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: UMASK
          value: "000"
        - name: PORT
          value: "8000"
        volumeMounts:
        - name: config-dir
          mountPath: /home/node/app/config
        - mountPath: "/home/node/app/data/default-user"
          subPath: "st/bitcherry"
          name: appdata
        - mountPath: "/home/node/app/plugins"
          subPath: "st/bitcherry/plugins"
          name: appdata
      
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"
spec:
  selector:
    app: "{{ .Release.Name }}-tavern"
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  name: "{{ .Release.Name }}-ingress"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - ryougi.ca
  rules:
  - host: tavern.kube.home.ryougi.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Release.Name }}-service"
            port:
              number: 80
  - host: tavern.kube.ryougi.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Release.Name }}-service"
            port:
              number: 80
  - host: tavern.home.ryougi.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Release.Name }}-service"
            port:
              number: 80
  - host: tavern.ryougi.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Release.Name }}-service"
            port:
              number: 80
