---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: satisfactory-deployment
  labels:
    app: satisfactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satisfactory
  template:
    metadata:
      labels:
        app: satisfactory
    spec:
      volumes:
      - name: satisfactory
        persistentVolumeClaim:
          claimName: satisfactory-pvc
      containers:
      - name: satisfactory
        image: wolveix/satisfactory-server:dev
        resources:
          requests:
            memory: "16Gi"
        ports:
        - containerPort: 7777
          protocol: UDP
        - containerPort: 15000
          protocol: UDP
        - containerPort: 15777
          protocol: UDP
        env:
        - name: MAXPLAYERS
          value: "8"
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: STEAMBETA
          value: "true"
        volumeMounts:
        - mountPath: "/config"
          name: satisfactory

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfactory-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1000Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: satisfactory-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1000Gi
  nfs:
    path: /mnt/user/appdata/satisfactory
    server: 192.168.1.20
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Available

---
apiVersion: v1
kind: Service
metadata:
  name: satisfactory-service
spec:
  type: NodePort
  selector:
    app: satisfactory
  ports:
    # Have to configure the router/load balancer/etc to direct 7777, 15000, 15777 to these nodeports
    - name: p1
      protocol: UDP
      port: 7777
      targetPort: 7777
      nodePort: 31777
    - name: p2
      protocol: UDP
      port: 15000
      targetPort: 15000
      nodePort: 31778
    - name: p3
      protocol: UDP
      port: 15777
      targetPort: 15777
      nodePort: 31779
