---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-deployment
  labels:
    app: uptime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime
  template:
    metadata:
      labels:
        app: uptime
    spec:
      volumes:
      - name: appdata
        persistentVolumeClaim:
          claimName: appdata-pvc
      containers:
      - name: uptime
        image: louislam/uptime-kuma
        ports:
        - containerPort: 3001
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: UMASK
          value: "000"
        volumeMounts:
        - mountPath: "/app/data"
          subPath: "uptime"
          name: appdata

---
apiVersion: v1
kind: Service
metadata:
  name: uptime-service
spec:
  selector:
    app: uptime
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: 3001

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  name: uptime-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - ryougi.ca
  - host: uptime.home.ryougi.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: uptime-service
            port:
              number: 3001
