apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-crocodile
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: crocodile
  project: default
  source:
    path: argocd/app-apps/crocodile
    repoURL: https://github.com/kumorikarasu/home.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true