---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: factoriotools/factorio:2.x
  name: app-factorio
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: apps
  project: default
  source:
    path: argocd/app-apps/factorio
    repoURL: https://github.com/kumorikarasu/home.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-factorio-secret
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: apps
  project: default
  source:
    path: argocd/app-apps/factorio-secret
    repoURL: https://github.com/kumorikarasu/home.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
