apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-runner
  namespace: argocd # Assuming you want to manage this app in the argocd namespace
spec:
  project: default # Or your specific project
  source:
    repoURL: https://github.com/kumorikarasu/home.git # Assuming your repo URL
    targetRevision: HEAD
    path: argocd/app-apps/github-runner
    plugin:
      name: sops-helm-skipcrds
  destination:
    server: https://kubernetes.default.svc
    namespace: actions-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
