apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-necesse
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: apps
  project: default
  source:
    path: argocd/app-apps/necesse
    repoURL: https://github.com/kumorikarasu/home.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
