apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: life
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kumorikarasu/life.git
    targetRevision: HEAD
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: simbru
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true