apiVersion: v1
kind: Secret
metadata:
  name: life-oauth-secrets
  namespace: simbru
type: Opaque
data:
  client-id: {{ .Values.oauth_client_id | b64enc | quote }}
  client-secret: {{ .Values.oauth_client_secret | b64enc | quote }}
  redirect-url: {{ .Values.oauth_redirect_url | b64enc | quote }}
