name: Docker Build DAGs
on:
  push:
    branches:
      - master

env:
  REPO_URL: "ghcr.io/kumorikarasu"

jobs: 
  build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Docker login
       uses: docker/login-action@v2.1.0
       with:
         registry: ${{ env.REPO_URL }}l
         username: kumorikarasu
         password: ${{ secrets.GH_PAT }}
     - name: Build Script
       env:
         GH_PAT: ${{ secrets.GH_PAT }}
       run: |
         cd docker/terraria
         chmod +x build.sh
         ./build.sh
