name: Docker Build DAGs
on:
  push:
    branches:
      - master

env:
  REPO_URL: "ghcr.io/kumorikarasu"

jobs: 
  build:
   runs-on: ubuntu-latest
   permissions: write-all
   steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Build Script
       env:
         GH_PAT: ${{ secrets.GH_PAT }}
         repo: ${{ github.repo }}
       run: |
         cd docker/terraria
         chmod +x build.sh
         ./build.sh

     - name: Get image tag
       run: |
        TAG=$(curl -sL https://api.github.com/repos/tModLoader/tModLoader/releases | jq -r "first | .tag_name")
        echo "TAG=$TAG" >> $GITHUB_ENV

     - name: Log in to GitHub Container Registry
       uses: docker/login-action@v3
       with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.GITHUB_TOKEN }} # important!

     - name: Build and push to Github registry
       run: |
         docker push ghcr.io/${{ github.repository_owner }}/tmodloader:${{ env.TAG }}
         docker push ghcr.io/${{ github.repository_owner }}/tmodloader:latest
