name: Docker Build DAGs
on:
  schedule: 
  - cron: '5 2 * * *'
  push:
    branches:
      - master

env:
  REPO_URL: "ghcr.io/kumorikarasu"

jobs: 
  build:
   runs-on: ubuntu-latest
   permissions: write-all
   steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Build Script
       env:
         GH_PAT: ${{ secrets.GH_PAT }}
         repo: ${{ github.repo }}
       run: |
         cd docker/terraria
         chmod +x build.sh
         ./build.sh
