nginx:
    tag: ENC[AES256_GCM,data:IEW9ugDj,iv:KmlUX7rewmQqJkX2Z3Auq0LmVTxulbom0LazSPcsd74=,tag:5RZSv9Uv4HEPpruf9bUMCA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ca-central-1:490881312659:key/9d2b0c80-354a-4705-8aea-e8053ada3b76
          created_at: "2023-01-26T17:34:31Z"
          enc: AQICAHjS4ENnSiVJmrdNfAAxWWjSzWh6nSsXgc38CA5Ml5cfJAEg2eeJd0P8eYbDcz8m6UlCAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMnjUFJER/Ubxn7gnqAgEQgDtY+kUC12kRakZ91ksLuhRIDtIqO5/5EE+TqGJhRQ2rXqL/PkIz+EgXGLUVJa00rWV1dN4cctvEDMWWrg==
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-26T17:34:32Z"
    mac: ENC[AES256_GCM,data:73zqBABeBP0NrUm3WkR0jh0bE3Y9laYgRuHOssEi6uDF2ts/IBcgaYTMRSo+uaRZ5xSNpSRFEgtNZ5e1YNgUOgRbKOKx1mLxYMPb9lYqQcNI9iYTh5tdtJ1Uv4H/zVihHb1dkua1l1uxCYUzskRkbfXEhwaHvZYtSvV/2fyIpz0=,iv:2GTIN7IXEpTelR/FGHkWYhOS82YDGgrezS7DVb/wC+c=,tag:wPKFD/grk9NkTYbOguZxJQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
