grafana:
  persistence:
    enabled: false

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.home.ryougi.ca
      - grafana.ryougi.ca
    path: /
    pathType: Prefix

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: monitoring
          type: prometheus
          access: proxy
          url: http://platform-grafana-prometheus-server.monitoring.svc:80
          isDefault: true
          editable: false
        - name: storage-sentinel
          type: prometheus
          access: proxy
          url: http://platform-storage-sentinel-prometheus-server.monitoring.svc:80
          isDefault: false
          editable: false

  grafana.ini:
    server:
      domain: grafana.ryougi.ca

prometheus:
  server:
    retention: 15d
    persistentVolume:
      enabled: true
      existingClaim: prometheus-data
      accessModes:
        - ReadWriteOnce
      size: 50Gi
      storageClass: ""
      volumeName: prometheus-platform-pv

    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - prometheus.home.ryougi.ca
        - prometheus.ryougi.ca
      paths:
        - /
      pathType: Prefix

  alertmanager:
    enabled: true
    persistence:
      enabled: false

platformStorage:
  csi:
    driver: csi.hpe.com
    fsType: xfs
    secretName: system-zvolcsi-truenas-secret
    secretNamespace: system-zvolcsi
    volumeAttributes:
      allowOverrides: sparse,compression,deduplication,volblocksize,sync,description
      compression: LZ4
      deduplication: "OFF"
      hostEncryption: "false"
      root: Backup/csi-volumes
      sync: STANDARD
      targetScope: volume
      volblocksize: 8K
      volumeAccessMode: mount

  prometheus:
    claimName: prometheus-data
    pvName: prometheus-platform-pv
    size: 50Gi
    reclaimPolicy: Retain
    selectorLabel: ryougi.ca/prometheus-storage
    selectorValue: monitoring-prometheus
    volumeHandle: Backup_csi-volumes_monitoring-prometheus
